//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudUsingFK_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string Course { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> Fess { get; set; }
        public Nullable<int> TrainerId { get; set; }
    
        public virtual trainer trainer { get; set; }
    }
}
